"""add_shared_ielts_speaking_bank

Revision ID: 1587253bc94c
Revises: 4d8b72f1c9aa
Create Date: 2026-09-30 17:17:58.393442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1587253bc94c'
down_revision: Union[str, Sequence[str], None] = '4d8b72f1c9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('chip', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wifi_ssid', sa.String(length=100), nullable=True),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_devices_chip'), 'edge_devices', ['chip'], unique=False)
    op.create_index(op.f('ix_edge_devices_ip_address'), 'edge_devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_edge_devices_status'), 'edge_devices', ['status'], unique=False)
    op.create_index(op.f('ix_edge_devices_user_id'), 'edge_devices', ['user_id'], unique=False)
    op.create_table('edge_firmware',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('chip', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_firmware_chip'), 'edge_firmware', ['chip'], unique=False)
    op.create_index(op.f('ix_edge_firmware_user_id'), 'edge_firmware', ['user_id'], unique=False)
    op.create_index(op.f('ix_edge_firmware_version'), 'edge_firmware', ['version'], unique=False)
    op.create_table('edge_ota_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('firmware_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['edge_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firmware_id'], ['edge_firmware.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_ota_tasks_device_id'), 'edge_ota_tasks', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_ota_tasks_status'), 'edge_ota_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_edge_ota_tasks_user_id'), 'edge_ota_tasks', ['user_id'], unique=False)
    op.alter_column('knowledge_categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('scenario_cards', sa.Column('ielts_part', sa.Integer(), nullable=True))
    op.add_column('scenario_cards', sa.Column('cue_card', sa.Text(), nullable=True))
    op.alter_column('scenario_cards', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('scenario_cards', 'difficulty',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'N5', 'N4', 'N3', 'N2', 'N1', name='scenariodifficulty', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_scenario_cards_ielts_part'), 'scenario_cards', ['ielts_part'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_cards_ielts_part'), table_name='scenario_cards')
    op.alter_column('scenario_cards', 'difficulty',
               existing_type=sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'N5', 'N4', 'N3', 'N2', 'N1', name='scenariodifficulty', native_enum=False),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.alter_column('scenario_cards', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('scenario_cards', 'cue_card')
    op.drop_column('scenario_cards', 'ielts_part')
    op.alter_column('knowledge_categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_edge_ota_tasks_user_id'), table_name='edge_ota_tasks')
    op.drop_index(op.f('ix_edge_ota_tasks_status'), table_name='edge_ota_tasks')
    op.drop_index(op.f('ix_edge_ota_tasks_device_id'), table_name='edge_ota_tasks')
    op.drop_table('edge_ota_tasks')
    op.drop_index(op.f('ix_edge_firmware_version'), table_name='edge_firmware')
    op.drop_index(op.f('ix_edge_firmware_user_id'), table_name='edge_firmware')
    op.drop_index(op.f('ix_edge_firmware_chip'), table_name='edge_firmware')
    op.drop_table('edge_firmware')
    op.drop_index(op.f('ix_edge_devices_user_id'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_status'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_ip_address'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_chip'), table_name='edge_devices')
    op.drop_table('edge_devices')
    # ### end Alembic commands ###
