"""drop capture / learning path / concept graph modules

2026-10-01 内容捕获（Capture）、学习路径与 5 分钟引导（LearningPath/PathMilestone）、
知识图谱（ConceptNode/ConceptEdge）三块功能整体下线，前后端代码已删除，这里清库表。

删除顺序按外键依赖倒排：
  1. cards.source_concept_id 外键指向 concept_nodes，先撤列（含索引）才能删 concept_nodes
  2. concept_edges → concept_nodes → path_milestones → learning_paths → captures
  3. user_profiles.onboarding_completed 原由 complete_onboarding 置位，引导下线后无人写入

Revision ID: a1c4e9f06b23
Revises: 1587253bc94c
Create Date: 2026-10-01 15:20:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1c4e9f06b23"
down_revision: str | Sequence[str] | None = "1587253bc94c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. cards.source_concept_id -> concept_nodes.id，必须先于 concept_nodes 删除
    op.drop_index(op.f("ix_cards_source_concept_id"), table_name="cards")
    op.drop_column("cards", "source_concept_id")

    # 2. concept_edges（自关联 concept_nodes）最先删
    op.drop_index(op.f("ix_concept_edges_target_id"), table_name="concept_edges")
    op.drop_index(op.f("ix_concept_edges_source_id"), table_name="concept_edges")
    op.drop_table("concept_edges")

    # 3. concept_nodes.capture_id -> captures.id，先于 captures 删
    op.drop_index(op.f("ix_concept_nodes_user_id"), table_name="concept_nodes")
    op.drop_index(op.f("ix_concept_nodes_capture_id"), table_name="concept_nodes")
    op.drop_table("concept_nodes")

    # 4. path_milestones -> learning_paths
    op.drop_index(op.f("ix_path_milestones_path_id"), table_name="path_milestones")
    op.drop_table("path_milestones")

    # 5. learning_paths
    op.drop_index(op.f("ix_learning_paths_user_id"), table_name="learning_paths")
    op.drop_table("learning_paths")

    # 6. captures
    op.drop_index(op.f("ix_captures_user_id"), table_name="captures")
    op.drop_table("captures")

    # 7. 引导流程下线
    op.drop_column("user_profiles", "onboarding_completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 2026-10-01 concept_nodes.embedding 需要 pgvector 类型，而 pgvector 依赖已随知识图谱下线删除。
    # 这里改为惰性导入：只有真的执行 downgrade 才需要它，正常 upgrade / alembic heads 不受影响。
    # 若未安装 pgvector 就跑 downgrade，会在这里得到明确的 ImportError。
    import pgvector.sqlalchemy

    op.add_column(
        "user_profiles",
        sa.Column(
            "onboarding_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.create_table(
        "captures",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "domain",
            sa.Enum(
                "LANGUAGE",
                "HUMANITIES",
                "SKILL",
                name="domain",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "TEXT",
                "URL",
                "PDF",
                name="capturesourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="capturestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_captures_user_id"), "captures", ["user_id"], unique=False
    )

    op.create_table(
        "learning_paths",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "domain",
            sa.Enum(
                "LANGUAGE",
                "HUMANITIES",
                "SKILL",
                name="domain",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "starting_point_report",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "COMPLETED",
                "ARCHIVED",
                name="learningpathstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_paths_user_id"), "learning_paths", ["user_id"], unique=False
    )

    op.create_table(
        "path_milestones",
        sa.Column("path_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "COMPLETED",
                "CURRENT",
                "LOCKED",
                name="pathmilestonestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "progress_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_path_milestones_path_id"), "path_milestones", ["path_id"], unique=False
    )

    op.create_table(
        "concept_nodes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("capture_id", sa.UUID(), nullable=True),
        sa.Column(
            "domain",
            sa.Enum(
                "LANGUAGE",
                "HUMANITIES",
                "SKILL",
                name="domain",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concept_nodes_capture_id"), "concept_nodes", ["capture_id"], unique=False
    )
    op.create_index(
        op.f("ix_concept_nodes_user_id"), "concept_nodes", ["user_id"], unique=False
    )

    op.create_table(
        "concept_edges",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "PREREQUISITE",
                "ANALOGY",
                "CONTRAST",
                "EXTENDS",
                name="conceptrelationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["concept_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["concept_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concept_edges_source_id"), "concept_edges", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_concept_edges_target_id"), "concept_edges", ["target_id"], unique=False
    )

    op.add_column(
        "cards",
        sa.Column("source_concept_id", sa.UUID(), nullable=True),
    )
    op.create_index(
        op.f("ix_cards_source_concept_id"), "cards", ["source_concept_id"], unique=False
    )
    op.create_foreign_key(
        "cards_source_concept_id_fkey",
        "cards",
        "concept_nodes",
        ["source_concept_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
